version : '3.8'
services:
  redis: 
   image: redis
   container_name: redis
   ports:
    - "6379:6379"
  db:
   image: postgres:9.4
   container_name: db
   ports:
     - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_USER: "postgres"
  votingapp:
    image: kodekloud/examplevotingapp_vote:v1
    continer_name : vote
    ports:
     - "5000:80"
    links:
     - redis:redis
  resultapp:
    image: kodekloud/examplevotingapp_result:v1
    container_name: result
    ports:
      - "5001:80"
    links:
       - db:db
  worker:
     image: kodekloud/examplevotingapp_worker:v1
     container_name: worker
     expose:
       -80
     links: 
       -db:db
       -redis:redis


